### ISSUE TITLE
Account for front-facing camera on Android phones

### ISSUE THREAD

**Issue by ericvw** [raffomania/knakk#1]
First, thanks for building and providing this great game. I came across this during my daily scan of https://lobste.rs/ the other day.

One UI issue I came across is the physical front-facing camera blocks the number of turns on the Pixel 6. Is it possible to have the entire UI shifted down or adjusted if it is possible to detect the area obscured by the camera?

I would contribute a PR, but I would need to familiarize myself with building games, the godot engine, and making Android applications, which I have no experience in 😕.

**Comment by raffomania** [comment]
Yes - this is on [the roadmap](https://github.com/users/raffomania/projects/1) already, and I have a rough idea on how I'll fix it. I've replaced my draft note with this issue so you'll be notified when this is completed :)

**Comment by ericvw** [comment]
Awesome — thank you for the response!

**Comment by raffomania** [comment]
I've just released version 1.0.2 with a fix, it should roll out in the play store over the next few days. If you get the chance to test, that would be great!

**Comment by ericvw** [comment]
The fix in 1.0.2 looks excellent — thank you very much!
