### ISSUE TITLE
[Suggestion] Keep track of personal best

### ISSUE THREAD

**Issue by FlyveHest** [raffomania/knakk#3]
No fancy high-scores, but it would be nice to keep track of the personal best on a given installation.

**Comment by raffomania** [comment]
Yes! [It's on the roadmap](https://github.com/users/raffomania/projects/1/views/1?pane=issue&itemId=25017478), but still in the backlog. At the moment, it's not a priority, but if other people request this I'd reconsider that :)

**Comment by FlyveHest** [comment]
I hadn't seen the roadmap, great to see that you are still working on the game, its a lot of fun.
